version: '1.0'
services:

  # mysql-server:
  #   image: mysql:8.0.36-bookworm
  #   # ports:
  #   #   - 3307:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=12345699
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql

  # redis-server:
  #   image: redis:7.2.4-bookworm
  #   # ports:
  #   #   - 6379:6379
  
  # proxy-server:
  #   build: ./proxy-server
  #   ports:
  #     - 8080:8081
  #   environment:
  #     - PROXY_PORT=8081
  #   depends_on:
  #     - mysql-server
  #     - redis-server
  #   volumes:
  #     - ./proxy-server:/app/proxy-server

  tunnel-server:
    build: ./tunnel-server
    ports:
      - 8799:8799
    environment:
      - TUNNEL_PORT=8799
    volumes:
      - ./tunnel-server:/app/tunnel-server
